name: Code-style

on:
  push:
    paths:
      - '**/*.php'
      - '.github/workflows/pint.yml'
  pull_request:
    paths:
      - '**/*.php'

jobs:
  pint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, json

      - name: Install composer dependencies
        run: composer install --no-interaction

      - name: Run Laravel Pint
        run: vendor/bin/pint --test